name: Pack
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: uplearn-complete
          path: src